_target_: align_system.algorithms.decision_flow_adm.math_reason_stage_component.MathReasonStageComponent

structured_inference_engine: ???
scenario_description_template: ???
system_prompt_template:
  _target_: align_system.prompt_engineering.outlines_prompts.DefaultITMBaselineSystemPrompt
prompt_template: ${template.prompt.decision_flow.math_reason}
output_schema_template: ${template.output_schema.decision_flow.math_reason}
attributes: ???
max_json_retries: 5