_target_: align_system.algorithms.decision_flow_adm.attribute_fine_grained_stage_component.AttributeFineGrainedStageComponent

structured_inference_engine: ${ref:adm.structured_inference_engine}
num_samples: 1
attributes: ${ref:adm.attribute_definitions}
max_json_retries: 5
system_prompt_template:
  _target_: align_system.prompt_engineering.outlines_prompts.DefaultITMBaselineSystemPrompt
