id: Feb2026-SS-5
kdma_values:
- kdma: search
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: -1.15
  - name: attr_weight
    value: 0.12813
  - name: medical_weight
    value: -1.71875
