id: Feb2026-AF6-PS8
kdma_values:
- kdma: affiliation
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 2.5125
  - name: attr_weight
    value: -0.64063
  - name: medical_weight
    value: 1.84375
- kdma: personal_safety
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 2.6125
  - name: attr_weight
    value: 1.4125
  - name: medical_weight
    value: 0.66125
