id: Feb2026-AF5-PS5
kdma_values:
- kdma: affiliation
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 2.1875
  - name: attr_weight
    value: 0.015625
  - name: medical_weight
    value: 2.36875
- kdma: personal_safety
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 0.2875
  - name: attr_weight
    value: 1.8825
  - name: medical_weight
    value: 0.46625
