id: Feb2026-MF3-SS1
kdma_values:
- kdma: merit
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 2.2125
  - name: attr_weight
    value: 1.8875
  - name: medical_weight
    value: 1.85
- kdma: search
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 1.65
  - name: attr_weight
    value: -0.715625
  - name: medical_weight
    value: -2.03125
