id: Feb2026-SS-1
kdma_values:
- kdma: search
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 1.65
  - name: attr_weight
    value: -0.715625
  - name: medical_weight
    value: -2.03125
