id: Feb2026-MF4-SS1
kdma_values:
- kdma: merit
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 2.8375
  - name: attr_weight
    value: -0.4875
  - name: medical_weight
    value: 2.45
- kdma: search
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 1.65
  - name: attr_weight
    value: -0.715625
  - name: medical_weight
    value: -2.03125
