id: Feb2026-MF3-SS7
kdma_values:
- kdma: merit
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 2.2125
  - name: attr_weight
    value: 1.8875
  - name: medical_weight
    value: 1.85
- kdma: search
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: -2.55
  - name: attr_weight
    value: -0.153125
  - name: medical_weight
    value: -0.78125
