id: Feb2026-AF2-PS2
kdma_values:
- kdma: affiliation
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 1.2125
  - name: attr_weight
    value: 0.671875
  - name: medical_weight
    value: 2.36875
- kdma: personal_safety
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: -2.0375
  - name: attr_weight
    value: 0.9425
  - name: medical_weight
    value: 0.36875
