id: Feb2026-AF5-PS8
kdma_values:
- kdma: affiliation
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 2.1875
  - name: attr_weight
    value: 0.015625
  - name: medical_weight
    value: 2.36875
- kdma: personal_safety
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 2.6125
  - name: attr_weight
    value: 1.4125
  - name: medical_weight
    value: 0.66125
