id: Feb2026-MF-8
kdma_values:
- kdma: merit
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 4.0875
  - name: attr_weight
    value: 1.4125
  - name: medical_weight
    value: 1.55
