id: Feb2026-MF-7
kdma_values:
- kdma: merit
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 4.0875
  - name: attr_weight
    value: 0.4625
  - name: medical_weight
    value: 1.85
