id: Feb2026-MF6-SS8
kdma_values:
- kdma: merit
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 3.4625
  - name: attr_weight
    value: 0.9375
  - name: medical_weight
    value: 2.45
- kdma: search
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: -3.25
  - name: attr_weight
    value: -1.278125
  - name: medical_weight
    value: -1.40625
