id: Feb2026-SS-8
kdma_values:
- kdma: search
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: -3.25
  - name: attr_weight
    value: -1.278125
  - name: medical_weight
    value: -1.40625
