id: Feb2026-AF-4
kdma_values:
- kdma: affiliation
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 1.8625
  - name: attr_weight
    value: -0.42188
  - name: medical_weight
    value: 2.10625
