id: Feb2026-AF-8
kdma_values:
- kdma: affiliation
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 2.8375
  - name: attr_weight
    value: 0.453125
  - name: medical_weight
    value: 2.10625
