id: Feb2026-AF3-PS2
kdma_values:
- kdma: affiliation
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 1.8625
  - name: attr_weight
    value: 0.015625
  - name: medical_weight
    value: 1.05625
- kdma: personal_safety
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: -2.0375
  - name: attr_weight
    value: 0.9425
  - name: medical_weight
    value: 0.36875
