id: Feb2026-AF4-PS3
kdma_values:
- kdma: affiliation
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 1.8625
  - name: attr_weight
    value: -0.42188
  - name: medical_weight
    value: 2.10625
- kdma: personal_safety
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: -1.2625
  - name: attr_weight
    value: 0.2375
  - name: medical_weight
    value: 0.75875
