id: Feb2026-AF-3
kdma_values:
- kdma: affiliation
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 1.8625
  - name: attr_weight
    value: 0.015625
  - name: medical_weight
    value: 1.05625
