id: Feb2026-MF3-SS8
kdma_values:
- kdma: merit
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 2.2125
  - name: attr_weight
    value: 1.8875
  - name: medical_weight
    value: 1.85
- kdma: search
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: -3.25
  - name: attr_weight
    value: -1.278125
  - name: medical_weight
    value: -1.40625
