id: Feb2026-PS-5
kdma_values:
- kdma: personal_safety
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 0.2875
  - name: attr_weight
    value: 1.8825
  - name: medical_weight
    value: 0.46625
