id: Feb2026-AF8-PS8
kdma_values:
- kdma: affiliation
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 2.8375
  - name: attr_weight
    value: 0.453125
  - name: medical_weight
    value: 2.10625
- kdma: personal_safety
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 2.6125
  - name: attr_weight
    value: 1.4125
  - name: medical_weight
    value: 0.66125
