_target_: align_system.algorithms.outlines_inference_engine.OutlinesTransformersInferenceEngine

model_name: mistralai/Mistral-7B-Instruct-v0.3
precision: half
max_generator_tokens: 8192
generation_kwargs:
  do_sample: false
  temperature: 0.0
